---
title: "CT Old Collections Interactive Map"
author: "James Mickley"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
graphics: yes
output: html_document
editor_options:
  chunk_output_type: console
---


```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```



```{r Main_Code, include = F, cache = F}

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Setup - This code is run, but output is hidden
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Load Packages
library(leaflet) # Needed for interactive maps

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Data Preparation
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


# Read in the specimens from species that haven't been collected recently
ct.old.collections <- read.csv("data/old-collections/ct-specimens.csv")

# Specimen url for the herbarium
herburl = "https://rbg-web2.rbge.org.uk/cgi-bin/nph-readbtree.pl/allspecs?&ETI="

```

Use the leaflet map below to explore the locations of specimens from species that have not been collected in the last 50 years.

```{r Map, echo = F}

# Construct an interactive leaflet map
leaflet(data = ct.old.collections, width = "100%", height = "550") %>% 
    
    # Set the view
    setView(lng = -72.7, lat = 41.5, zoom = 9) %>% 
    
    # Add 3 different maptypes
    addTiles(group = "OpenStreeMap") %>%
    addProviderTiles("OpenTopoMap", group = "OpenTopoMap") %>%
    addProviderTiles("Esri.WorldImagery", group = "Esri_Satellite") %>% 
    
    # Add a layers chooser control to choose different map layers
    addLayersControl(
        baseGroups = c("OpenStreeMap", "OpenTopoMap", 
            "Esri_Satellite"),
        position = "topleft",
        options = layersControlOptions(collapsed = T)
    ) %>%
    
    # Add markers for each specimen, with a popup containing name/year/barcode
    addMarkers(~decimalLongitude, ~decimalLatitude, 
        popup = ~paste(
            as.character(scientificName),
            paste("Collected:", year),
            paste0('<a href = "',herburl, as.character(catalogNumber),
               '" target = "_blank">', as.character(catalogNumber), "</a>"), 
            sep = "<br/>"), 
        clusterOptions = markerClusterOptions())

```
